### ISSUE TITLE
Wiggle PV live values

### ISSUE THREAD

**Issue by peterdudfield** [SheffieldSolar/PV_Live-API#17]
We noticed that some values are very wiggly, are these values correct

![Screenshot 2022-09-09 at 12 52 02](https://user-images.githubusercontent.com/34686298/189343921-3bb6d358-5dca-4800-b470-a9735f425492.png)

**Comment by ejones18** [comment]
Hi Peter, I believe this a query about the PV_Live methodology rather than the source code - I will close this issue, but feel free to reach out to one of the team if you need a response. Ta
