### ISSUE TITLE
Update installed capacity?

### ISSUE THREAD

**Issue by peterdudfield** [SheffieldSolar/PV_Live-API#19]
Just wondering if there are any plans to update the installed capacity.

![Screenshot 2023-03-22 at 08 17 05](https://user-images.githubusercontent.com/34686298/226840768-fd456695-3cf1-408b-98ec-e8e752b4068a.png)

Complete understand if you are busy s.t.c

**Comment by JamieTaylor-TUOS** [comment]
@peterdudfield A capacity update is being derived at the moment - we'll notify everyone via the PV_Live user mailing list once we have a deployment date
