### ISSUE TITLE
Update to new url

### ISSUE THREAD

**Issue by peterdudfield** [SheffieldSolar/PV_Live-API#45]
Would you be able to update the urls in this pacakage and realease to pypi.

Inparticualr I think https://github.com/SheffieldSolar/PV_Live-API/blob/main/pvlive_api/pvlive.py#L51, is using he old url

We noticed this on 2024-12-17 when the old url was down, but the new url was working

**Comment by JamieTaylor-TUOS** [comment]
Would #34 address this?

**Comment by peterdudfield** [comment]
Yes. 

Could you release to pypi?

**Comment by JamieTaylor-TUOS** [comment]
Will do asap

**Comment by peterdudfield** [comment]
Thanks, let me know when its been done please

**Comment by JamieTaylor-TUOS** [comment]
@peterdudfield Done, see https://pypi.org/project/pvlive-api/1.4.0/
