### ISSUE TITLE
GSP ids

### ISSUE THREAD

**Issue by peterdudfield** [SheffieldSolar/PV_Live-API#8]
Is there an easy endpoint to get all the gsp ids, or pes ids?

This might be quite handy if people want to then get data points from different sites.

Can probably force a method to try ids until they stop working, but there might be an easy sql command on the server side of this API that might be better to use

My motivation is to move 
https://github.com/openclimatefix/nowcasting_dataset/blob/main/nowcasting_dataset/data_sources/gsp/pvlive.py
these functions to this repo so lots of people can use them

**Comment by JamieTaylor-TUOS** [comment]
There's an instance attribute: `self.gsp_ids` (numpy array of unique int IDs)

Also one for PES IDs: `self.pes_ids` (numpy array of unique int IDs)

There's also a lookup of all modelled entities, from which both of are derived: `self.ggd_lookup` (Pandas DF)

e.g. 

```python
from pvlive_api import PVLive

pvl = PVLive()
print(pvl.gsp_ids)
```

**Comment by JamieTaylor-TUOS** [comment]
(Apologies they're not documented in the README, I'll add this...)

**Comment by peterdudfield** [comment]
ah thanks - thats super
